apiVersion: v2
maintainers:
  - name: Kenneth Martens
    email: kenneth.martens@proton.me
name: cert-manager
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: cert-manager
    repository: "https://charts.jetstack.io"
    version: 1.9.1

