apiVersion: v2
name: keycloak
description: A Helm chart for Kubernetes
type: application

version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: keycloak
    repository: "https://codecentric.github.io/helm-charts"
    version: 18.3.0
