apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.clusterName }}
spec:
  kafka:
    version: 3.2.0
    replicas: {{ .Values.kafka.instances }}
    listeners:
      - name: plain
        port: {{ .Values.kafka.listeners.plain.port }}
        type: internal
        tls: false
      - name: tls
        port: {{ .Values.kafka.listeners.tls.port }}
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka.storage.volume.size }}
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: {{ .Values.zookeeper.storage.volume.size }}
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}